"""2

Revision ID: 113f1d770847
Revises: d4b356a46caf
Create Date: 2026-08-08 10:41:30.063605

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '113f1d770847'
down_revision: Union[str, Sequence[str], None] = 'd4b356a46caf'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(op.f('tasks_executor_id_fkey'), 'tasks', type_='foreignkey')
    op.drop_column('tasks', 'executor_id')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('tasks', sa.Column('executor_id', sa.BIGINT(), autoincrement=False, nullable=False))
    op.create_foreign_key(op.f('tasks_executor_id_fkey'), 'tasks', 'users', ['executor_id'], ['id'], ondelete='CASCADE')
    # ### end Alembic commands ###
