"""change task structure and add project

Revision ID: 18f93d5ff757
Revises: b8bcc812d01b
Create Date: 2026-09-14 10:31:24.964504

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql


# revision identifiers, used by Alembic.
revision: str = '18f93d5ff757'
down_revision: Union[str, Sequence[str], None] = 'b8bcc812d01b'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


task_status = postgresql.ENUM(
    'to_do', 'in_progress', 'review', 'completed', name='task_status'
)
task_priority = postgresql.ENUM(
    'low', 'medium', 'high', name='task_priority'
)


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    bind = op.get_bind()
    task_status.create(bind, checkfirst=True)
    task_priority.create(bind, checkfirst=True)

    op.create_table('projects',
    sa.Column('id', sa.BigInteger(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('description', sa.String(), nullable=False),
    sa.Column('owner_id', sa.BigInteger(), nullable=True),
    sa.ForeignKeyConstraint(['owner_id'], ['users.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_projects_id'), 'projects', ['id'], unique=False)
    op.create_index(op.f('ix_projects_owner_id'), 'projects', ['owner_id'], unique=False)
    op.add_column('tasks', sa.Column('status', task_status, server_default='to_do', nullable=False))
    op.add_column('tasks', sa.Column('priority', task_priority, server_default='medium', nullable=False))
    op.add_column('tasks', sa.Column('project_id', sa.BigInteger(), nullable=True))
    op.create_index(op.f('ix_tasks_project_id'), 'tasks', ['project_id'], unique=False)
    op.create_foreign_key(
        'fk_tasks_project_id_projects',
        'tasks',
        'projects',
        ['project_id'],
        ['id'],
        ondelete='CASCADE',
    )
    op.execute(
        "UPDATE tasks SET status = 'completed' WHERE completed IS TRUE"
    )
    op.drop_column('tasks', 'completed')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        'tasks',
        sa.Column(
            'completed',
            sa.BOOLEAN(),
            server_default=sa.text('false'),
            autoincrement=False,
            nullable=False,
        ),
    )
    op.execute(
        "UPDATE tasks SET completed = TRUE WHERE status = 'completed'"
    )
    op.drop_constraint(
        'fk_tasks_project_id_projects', 'tasks', type_='foreignkey'
    )
    op.drop_index(op.f('ix_tasks_project_id'), table_name='tasks')
    op.drop_column('tasks', 'project_id')
    op.drop_column('tasks', 'priority')
    op.drop_column('tasks', 'status')
    bind = op.get_bind()
    task_priority.drop(bind, checkfirst=True)
    task_status.drop(bind, checkfirst=True)
    op.drop_index(op.f('ix_projects_owner_id'), table_name='projects')
    op.drop_index(op.f('ix_projects_id'), table_name='projects')
    op.drop_table('projects')
    # ### end Alembic commands ###
