"""add role to user

Revision ID: 560919c35e64
Revises: 18f93d5ff757
Create Date: 2026-09-19 05:48:36.974201

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql



# revision identifiers, used by Alembic.
revision: str = '560919c35e64'
down_revision: Union[str, Sequence[str], None] = '18f93d5ff757'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None

user_role = postgresql.ENUM(
    'admin', 'manager', 'user', name='user_role'
)


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    bind = op.get_bind()

    user_role.create(bind, checkfirst=True)
    op.add_column('users', sa.Column('role', user_role, server_default='user', nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    bind = op.get_bind()
    op.drop_column('users', 'role')
    user_role.drop(bind, checkfirst=True)
    # ### end Alembic commands ###
