"""add default for completed

Revision ID: b8bcc812d01b
Revises: 052252715f9f
Create Date: 2026-08-25 09:23:18.278146

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'b8bcc812d01b'
down_revision: Union[str, Sequence[str], None] = '052252715f9f'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    op.alter_column(
        "tasks",
        "completed",
        existing_type=sa.Boolean(),
        server_default=sa.text("false"),
        existing_nullable=False,
    )


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column(
        "tasks",
        "completed",
        existing_type=sa.Boolean(),
        server_default=None,
        existing_nullable=False,
    )
    # ### end Alembic commands ###
