"""3

Revision ID: d3a2e7b12dbb
Revises: 113f1d770847
Create Date: 2026-08-08 10:45:59.764810

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'd3a2e7b12dbb'
down_revision: Union[str, Sequence[str], None] = '113f1d770847'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('tasks', sa.Column('executor_id', sa.BigInteger(), nullable=True))
    op.create_foreign_key(None, 'tasks', 'users', ['executor_id'], ['id'], ondelete='CASCADE')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'tasks', type_='foreignkey')
    op.drop_column('tasks', 'executor_id')
    # ### end Alembic commands ###
